# Generated by Django 5.2.17 on 2026-09-04 17:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kicker', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('cta_label', models.CharField(default='View →', max_length=20)),
                ('cta_type', models.CharField(choices=[('sku', 'SKU'), ('url', 'URL'), ('anchor', 'Anchor')], default='anchor', max_length=10)),
                ('cta_value', models.CharField(default='brown-sugar', max_length=256)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_active', models.BooleanField()),
                ('to_active', models.BooleanField()),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banner_events',
                'ordering': ['at'],
            },
        ),
    ]
