# Generated by Django 5.2.17 on 2026-09-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banners', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bannerevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannerevent',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='banners.banner'),
        ),
        migrations.AddField(
            model_name='bannerevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_events', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['tenant', 'is_active'], name='banners_tenant__5166d0_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['tenant', 'sort'], name='banners_tenant__9aae85_idx'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'sort'), name='uniq_tenant_sort_active'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='chk_ends_after_starts'),
        ),
    ]
