# Generated by Django 5.2.17 on 2026-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='media_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
