# Generated by Django 5.2.17 on 2026-09-05 13:28

from django.db import migrations, models


def drop_sku_cta(apps, schema_editor):  # type: ignore[no-untyped-def]
    BannerSlide = apps.get_model("banners", "BannerSlide")
    BannerSlide.objects.filter(cta_type="sku").update(cta_type="anchor")


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0004_bannerslide_alter_banner_options_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_sku_cta, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bannerslide",
            name="cta_type",
            field=models.CharField(choices=[("url", "URL"), ("anchor", "Anchor")], default="anchor", max_length=10),
        ),
        migrations.AlterField(
            model_name="bannerslide",
            name="cta_value",
            field=models.CharField(default="", max_length=256),
        ),
    ]