# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations


def drop_sku_cta(apps, schema_editor):  # type: ignore[no-untyped-def]
    BannerSlide = apps.get_model("banners", "BannerSlide")
    BannerSlide.objects.filter(cta_type="sku").update(cta_type="anchor")


def restore_sku_cta(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Irreversible data fix — reversing leaves rows normalized at anchor."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0005_alter_bannerslide_cta_type_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_sku_cta, restore_sku_cta),
    ]