# Generated by Django 5.2.17 on 2026-09-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_fixup_drop_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerslide',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='bannerslide',
            name='cta_type',
        ),
        migrations.RemoveField(
            model_name='bannerslide',
            name='cta_value',
        ),
    ]
