# Generated by Django 5.2.17 on 2026-09-04 17:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=32)),
                ('from_value', models.CharField(blank=True, max_length=256, null=True)),
                ('to_value', models.CharField(blank=True, max_length=256, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_events',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_key', models.CharField(blank=True, max_length=256, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sort', 'name'],
            },
        ),
    ]
