# Generated by Django 5.2.17 on 2026-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_image_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
