# Generated by Django 5.2.17 on 2026-09-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_events', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='orders_tenant__ed6a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pickup_code'], name='orders_pickup__7a5ee1_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('pickup_code__isnull', False), ('status', 'AWAITING_PICKUP')), fields=('pickup_code',), name='uniq_pickup_code_awaiting'),
        ),
    ]
