# Generated by Django 5.2.17 on 2026-09-04 17:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('slot_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('booked', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_slots', to='tenants.tenant')),
            ],
            options={
                'db_table': 'batch_slots',
                'ordering': ['slot_time'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='batch_slots_tenant__f11f77_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku', 'slot_time'), name='uniq_tenant_sku_slot')],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='tenants.tenant')),
            ],
            options={
                'db_table': 'opening_hours',
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day_of_week'), name='uniq_tenant_dow')],
            },
        ),
    ]
